# Generated by Django 5.0.6 on 2024-06-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('point_counter', models.PositiveIntegerField(default=0)),
                ('position_counter', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
