# Generated by Django 5.0.6 on 2024-06-23 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='email',
            new_name='name',
        ),
    ]
